block: install libtcmu too, along with tcmu-runner (#51)
Fix the below error which is stopping the script.

error: Failed dependencies:
libtcmu = 1.4.0.83.g9d8a7e9-0.el7 is needed by tcmu-runner-1.4.0.83.g9d8a7e9-0.el7.x86_64
libtcmu.so.2()(64bit) is needed by tcmu-runner-1.4.0.83.g9d8a7e9-0.el7.x86_64