Add tasks to install pytest version 6.1.2 and py version 1.9.0
Problem:
With the pytest version 6.2.1 doClassCleanups() are failing in glusto with the below error:
```
TypeError: _is_error_or_failure_exists() missing 1 required positional argument: 'self'
```

Fix:
Install pytest version 6.1.2 and py version 1.9.0 which can be removed one the issue is fixed in pytest